/*
  ____  _       _            _             _
 / ___|(_)_ __ | | __  _ __ | |_   _  __ _(_)_ __
 \___ \| | '_ \| |/ / | '_ \| | | | |/ _` | | '_ \
  ___) | | | | |   <  | |_) | | |_| | (_| | | | | |
 |____/|_|_| |_|_|\_\ | .__/|_|\__,_|\__, |_|_| |_|
                      |_|            |___/
# A Template for ValidatorPlugin, a Sink Plugin
# Generated by the command: plugin -t sink -d validator_plugin validator
# Hostname: Fram-IV.local
# Current working directory: /Users/p4010/Develop/MADS_plugins
# Creation date: 2026-06-03T15:44:12.624+0200
# NOTICE: MADS Version 2.1.0
*/

// Mandatory included headers
#include <nlohmann/json-schema.hpp>
#include <nlohmann/json.hpp>
#include <pugg/Kernel.h>
#include <sink.hpp>

// other includes as needed here
#include <fstream>
#include <iomanip>
#include <memory>
#include <stdexcept>

// Define the name of the plugin
#ifndef PLUGIN_NAME
#define PLUGIN_NAME "validator"
#endif

// Load the namespaces
using namespace std;
using json = nlohmann::json;
using nlohmann::json_schema::json_validator;

// Plugin class. This shall be the only part that needs to be modified,
// implementing the actual functionality
class ValidatorPlugin : public Sink<json> {

public:
  // Don't forget to inherit the constructors of the parent class
  // If you really need to implement your own constructor, make sure to call
  // the parent constructor. Normally, use set_params() to set the parameters
  // instead of the constructor.
  using Sink::Sink; // inherit constructors

  // Typically, no need to change this
  string kind() override { return PLUGIN_NAME; }

  // Implement the actual functionality here
  // Return types:
  // return_type::success: processing is valid
  // return_type::retry: skip processing go to next loop
  // return_type::warning: content of _error is tracked with register_event
  // return_type::error: _error is traced, skip process
  // return_type::critical: execution stops
  return_type load_data(json const &input, string topic = "",
                        vector<unsigned char> const *blob = nullptr) override {
    if (_set_params_failed) {
      _error = "Failed to set parameters, cannot process data.";
      return return_type::critical;
    }
    if (topic == "agent_event") {
      return return_type::retry; // skip processing agent_event to avoid potential infinite loop
    }
    /* AGENT
    Implement the actual validation logic here. You can use the _schemas
    variable to access the loaded schemas, and you can set the _error variable
    if there is an error during validation. Also, print informative messages to
    the console for debugging purposes.
    */
    auto validator_it = _validators.find(topic);
    if (validator_it == _validators.end()) {
      _error = "No schema configured for topic '" + topic + "'.";
      cerr << "[validator] " << _error << endl;
      return return_type::warning;
    }

    try {
      validator_it->second->validate(input);
    } catch (const std::exception &e) {
      _error = "Message on topic '" + topic +
               "' does not comply with schema: " + string(e.what());
      cerr << "[validator] " << _error << endl;
      cerr << "[validator] Message: " << input.dump() << endl;
      return return_type::error;
    }

    return return_type::success;
  }

  void set_params(const json &params) override {
    Sink::set_params(params);
    _set_params_failed = false;
    _error.clear();
    _schemas = json::object();
    _validators.clear();
    _params["schemas"] = "schemas.json"; // default file name
    _params.merge_patch(params);
    try {
      string schema_path = "schemas.json";
      const json &schemas_param = _params.at("schemas");

      if (schemas_param.is_object()) {
        _schemas = schemas_param;
        _params["schemas"] = schema_path;
      } else if (schemas_param.is_string()) {
        const string schemas_value = schemas_param.get<string>();
        try {
          _schemas = json::parse(schemas_value);
          _params["schemas"] = schema_path;
        } catch (const json::parse_error &) {
          schema_path = schemas_value;
          ifstream schema_file(schema_path);
          if (!schema_file) {
            throw runtime_error("Cannot open schema file '" + schema_path +
                                "'.");
          }
          schema_file >> _schemas;
          _params["schemas"] = schema_path;
        }
      } else {
        throw runtime_error(
            "'schemas' must be a schema file path, JSON string, or object.");
      }

      if (!_schemas.is_object()) {
        throw runtime_error(
            "Schema registry must be a JSON object keyed by topic.");
      }

      ofstream schema_file(_params.at("schemas").get<string>());
      if (!schema_file) {
        throw runtime_error("Cannot write schema file '" +
                            _params.at("schemas").get<string>() + "'.");
      }
      schema_file << setw(2) << _schemas << '\n';
    } catch (const std::exception &e) {
      cerr << "Error parsing schemas: " << e.what() << endl;
      _error = "Error parsing schemas: " + string(e.what());
      _set_params_failed = true;
      return;
    }
    /* AGENT
    Further initializatuions here. For example, you might setup _validator
    and validate the schema file itself against
    ValidatorPlugin::schema_of_schemas
    */
    try {
      for (auto const &[topic, schema] : _schemas.items()) {
        if (!schema.is_object()) {
          throw runtime_error("Schema for topic '" + topic +
                              "' must be a JSON object.");
        }

        auto validator = std::make_unique<json_validator>(
            nullptr, nlohmann::json_schema::default_string_format_check);
        validator->set_root_schema(schema);
        _validators[topic] = std::move(validator);
      }
    } catch (const std::exception &e) {
      _error = "Invalid schema registry: " + string(e.what());
      cerr << "[validator] " << _error << endl;
      _set_params_failed = true;
      return;
    }

    cout << "[validator] Loaded " << _schemas.size() << " schema(s) from '"
         << _params.at("schemas").get<string>() << "'." << endl;
  }

  // Implement this method if you want to provide additional information
  map<string, string> info() override {
    return {{"Schema file", _params["schemas"].get<string>()}};
  };

private:
  json _schemas =
      json::object(); // if you want to use schemas, you can store them here
  map<string, unique_ptr<json_validator>> _validators;
  bool _set_params_failed = false; // if you want to track if set_params failed,
                                   // you can use this variable
};

/*
  ____  _             _             _      _
 |  _ \| |_   _  __ _(_)_ __     __| |_ __(_)_   _____ _ __
 | |_) | | | | |/ _` | | '_ \   / _` | '__| \ \ / / _ \ '__|
 |  __/| | |_| | (_| | | | | | | (_| | |  | |\ V /  __/ |
 |_|   |_|\__,_|\__, |_|_| |_|  \__,_|_|  |_| \_/ \___|_|
                |___/
Enable the class as plugin
*/
MADS_REGISTER_PLUGINS(ValidatorPlugin)

/*
                  _
  _ __ ___   __ _(_)_ __
 | '_ ` _ \ / _` | | '_ \
 | | | | | | (_| | | | | |
 |_| |_| |_|\__,_|_|_| |_|

For testing purposes, when directly executing the plugin
*/
int main(int argc, char const *argv[]) {
  ValidatorPlugin plugin;
  /* AGENT
  Implement a test case here. For example, you can load schemas.json and some
  data, and call the load_data method to see if the validation works as
  expected. Also, print the results to the console for debugging purposes.
  */
  plugin.set_params(json::object());

  const json valid_temperature = {
      {"time", "2026-06-03T12:00:00Z"},
      {"value", 24.2},
  };
  const json invalid_temperature = {
      {"time", "not-a-date-time"},
      {"value", "hot"},
  };

  const auto valid_result = plugin.load_data(valid_temperature, "temperature");
  cout << "Valid temperature result: " << static_cast<int>(valid_result)
       << endl;

  const auto invalid_result =
      plugin.load_data(invalid_temperature, "temperature");
  cout << "Invalid temperature result: " << static_cast<int>(invalid_result)
       << endl;

  const auto missing_schema_result =
      plugin.load_data(valid_temperature, "humidity");
  cout << "Missing schema result: " << static_cast<int>(missing_schema_result)
       << endl;

  return 0;
}
